# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "soroban"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jason Hutchens"]
  s.date = "2012-04-23"
  s.description = "Soroban makes it easy to extract and execute formulas from Excel spreadsheets. It rewrites Excel formulas as Ruby expressions, and allows you to bind named variables to spreadsheet cells to easily manipulate inputs and capture outputs."
  s.email = "jason.hutchens@agworld.com.au"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".yardopts",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "Soroban.gemspec",
    "VERSION",
    "lib/soroban.rb",
    "lib/soroban/cell.rb",
    "lib/soroban/error.rb",
    "lib/soroban/functions.rb",
    "lib/soroban/functions/and.rb",
    "lib/soroban/functions/average.rb",
    "lib/soroban/functions/if.rb",
    "lib/soroban/functions/max.rb",
    "lib/soroban/functions/min.rb",
    "lib/soroban/functions/not.rb",
    "lib/soroban/functions/or.rb",
    "lib/soroban/functions/sum.rb",
    "lib/soroban/functions/vlookup.rb",
    "lib/soroban/helpers.rb",
    "lib/soroban/parser.rb",
    "lib/soroban/parser/grammar.rb",
    "lib/soroban/parser/grammar.treetop",
    "lib/soroban/parser/nodes.rb",
    "lib/soroban/parser/rewrite.rb",
    "lib/soroban/sheet.rb",
    "lib/soroban/walker.rb",
    "spec/soroban_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/agworld/soroban"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Soroban is a calculating engine that understands Excel formulas."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<treetop>, ["~> 1.4.10"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rubyXL>, ["~> 1.2.7"])
      s.add_development_dependency(%q<redcarpet>, [">= 0"])
    else
      s.add_dependency(%q<treetop>, ["~> 1.4.10"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rubyXL>, ["~> 1.2.7"])
      s.add_dependency(%q<redcarpet>, [">= 0"])
    end
  else
    s.add_dependency(%q<treetop>, ["~> 1.4.10"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.1.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rubyXL>, ["~> 1.2.7"])
    s.add_dependency(%q<redcarpet>, [">= 0"])
  end
end

